---
# Source: https://pre-commit.com/hooks.html
# pre-commit install
# pre-commit autoupdate
# pre-commit run --all-files --verbose
# detect-secrets scan > .secrets.baseline
# safety auth login
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # name: pre-commit-hooks (out-of-the-box hooks for pre-commit)
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        description: Trims trailing whitespace.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
        # exclude: .cache_ggshield
      - id: double-quote-string-fixer
        verbose: true
      - id: debug-statements
        verbose: true
      - id: name-tests-test
        verbose: true
      - id: requirements-txt-fixer
        verbose: true
      - id: check-added-large-files
        args: [--maxkb=10000]
        verbose: true
        log_file: "true"
      - id: check-ast
        verbose: true
      - id: check-builtin-literals
        verbose: true
      - id: check-xml
        verbose: true
      - id: check-yaml
        verbose: true
        args: [--allow-multiple-documents]
        exclude: .pre-commit-config.yaml | */values.yaml
      - id: pretty-format-json
        verbose: true
        args: [--autofix]
        exclude: '^.vscode/'
      - id: check-json
        verbose: true
        exclude: '^.vscode/'
      - id: check-merge-conflict
        verbose: true
      - id: check-vcs-permalinks
        verbose: true
        exclude:  .pre-commit-config.yaml | */values.yaml
      - id: forbid-new-submodules
        verbose: true
      - id: no-commit-to-branch
        verbose: true
        args: [--branch, master]
      - id: check-executables-have-shebangs
        verbose: true
      - id: mixed-line-ending
        verbose: true
        args: [--fix=lf]
      - id: detect-aws-credentials
        verbose: true
        args: ['--allow-missing-credentials']
      - id: detect-private-key
        verbose: true
        exclude: gitleaks-report.json

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-crlf
        name: pre-commit-hooks (Lucas-C - useful git hooks)
        verbose: true
      - id: remove-crlf
        description: Remove CRLF Line breaks
        exclude: .pre-commit-config.yaml
      - id: forbid-tabs
        verbose: true
      - id: remove-tabs
        name: pre-commit-hooks (Lucas-C - useful git hooks)
        verbose: true
        args: [--whitespaces-count, "2"] # defaults to: 4

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v3.2.0
    hooks:
      - id: setup-cfg-fmt
        name: setup-cfg-fmt (apply a consistent format to setup.cfg files)

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: [-l, -i, "2", -ci, -sr, -w]
        verbose: true
      - id: shellcheck
        verbose: true

  - repo: https://github.com/crate-ci/typos
    rev: v1.50.3
    hooks:
      - id: typos
        name: typos (Finds and corrects spelling mistakes)
        args: ["--config", ".typos.toml", "-v"]
        exclude: gitleaks-report.json|values\.yaml|jenkins/example-values-jenkins.yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # https://prettier.io/docs/en/options.html#parser
        files: .json5$

  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.19.1
    hooks:
      - id: yamlfix
        exclude: .pre-commit-config.yaml|values\.yaml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: yamllint (linter for YAML files)
        args: [--format, auto]
        exclude: .pre-commit-config.yaml|values\.yaml

#   - repo: https://github.com/pre-commit/pygrep-hooks
#     rev: v1.10.0
#     hooks:
#       - id: python-no-log-warn
#       - id: python-no-eval
#       - id: rst-backticks
#       - id: rst-directive-colons
#       - id: rst-inline-touching-normal
#       - id: text-unicode-replacement-char
#         name: pygrep-hooks (collection of fast, cheap, regex based pre-commit hooks.)

#   - repo: https://github.com/PyCQA/flake8
#     rev: 7.1.2
#     hooks:
#       - id: flake8
#         name: flake8 (Flake8 is a wrapper around these tools PyFlakes, pycodestyle, McCabe script)
#         # exclude:

#   - repo: local
#     hooks:
#       - id: python-safety-dependencies-check
#         name: safety
#         entry: safety
#         args: [scan, --apply-fixes] # --full-report
#         language: system
#         files: requirements

#   - repo: https://github.com/seddonym/import-linter
#     rev: v2.3
#     hooks:
#       - id: import-linter
#         name: import-linter (define and enforce rules for the imports within and between Python packages)

#   - repo: https://github.com/hhatto/autopep8
#     rev: v2.3.2
#     hooks:
#       - id: autopep8
#         name: autopep8 (Style Guide Enforcement)

#   - repo: https://github.com/landscapeio/prospector
#     rev: v1.15.3
#     hooks:
#       - id: prospector
#         name: prospector (Style Guide Enforcement)
#         # exclude:

#   - repo: https://github.com/asottile/reorder-python-imports
#     rev: v3.14.0
#     hooks:
#       - id: reorder-python-imports
#         name: reorder-python-imports (Tool for automatically reordering python imports)
#         args: [--py39-plus, --add-import, from __future__ import annotations]
#         # exclude:

#   - repo: https://github.com/twu/skjold
#     rev: v0.6.2
#     hooks:
#       - id: skjold
#         name: skjold (Security audit python project dependencies against several security advisory databases)
#         args: [--sources, pypa] # gemnasium|github|osv|pypa|pyup

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        name: bandit (security linter in Python code)
        # args: ["-s", ""]

  - repo: https://github.com/PeterMosmans/jenkinslint
    rev: v1.0.0
    hooks:
      - id: jenkinslint
        name: jenkinslint (basic Jenkinsfile linter)

  # - repo: https://github.com/terraform-docs/terraform-docs
  #   rev: v0.19.0
  #   hooks:
  #     - id: terraform-docs-go
  #       args: [markdown, table, --output-file, README.md, ./]
  #       args: [--args=--config=.terraform-docs.yml]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.109.2
    hooks:
      - id: terraform_fmt
        verbose: true
        # args: [--hook-config=--parallelism-ci-cpu-cores=1]
      - id: terraform_tflint
        verbose: true
      # args: [--minimum-failure-severity=[notice,warning]]
      # args: [--hook-config=--parallelism-ci-cpu-cores=1]
      - id: terraform_validate
        verbose: true
      - id: terraform_trivy
        verbose: true
      # files: ^prd-infra/
      - id: terraform_providers_lock
        verbose: true
        # args: [--hook-config=--parallelism-limit=CPU*4]
      # - id: terraform_checkov
      #   verbose: true
      #   args: ["--config-file", ".checkov.yaml"]
        # args: [--args=--quiet, --args=--skip-check CKV2_AWS_8]
      # - id: infracost_breakdown
      #   args:
      #     - --args=--path=./terraform
      #   verbose: true

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        name: dockerfilelint-precommit-hooks (Useful pre-commit hooks for checking Dockerfiles)
        stages: [pre-commit]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.15.1
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        entry: hadolint
        args:
          [
            "--ignore",
            "DL3007",
            "--ignore",
            "DL3013",
            "--ignore",
            "DL3027",
            "--ignore",
            "DL3059",
            "--ignore",
            "DL4006",
            "--ignore",
            "SC1091",
            "--ignore",
            "SC2015",
            "--ignore",
            "SC3037",
          ]

  # - repo: https://github.com/dmitri-lerko/pre-commit-docker-kustomize
  #   rev: f3a8533
  #   hooks:
  #       - id: kustomize
  #         name: kustomize-development
  #         description: pre-commit hook which runs kustomize docker image
  #         args: [overlays/development]
  #         verbose: false

  - repo: https://github.com/zwennesm/pre-commit-k8s
    rev: 0.0.3
    hooks:
      - id: pre-commit-k8s
        entry: pre-commit-k8s
        exclude: postgresql-secret.yaml|jenkins-secret.yaml

  - repo: https://github.com/stackrox/kube-linter
    rev: v0.8.3 # kube-linter version
    hooks:
      - id: kube-linter
        name: kube-linter (static analysis tool for Kubernetes YAML files)
        args: [-v]
        files: .yaml$
        # exclude:

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        name: helm-docs (auto-generates documentation from helm charts into markdown)
        # exclude:

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets (module for detecting secrets)
        args:
          - --baseline
          - .secrets.baseline
          - --disable-plugin
          - KeywordDetector
        # exclude:

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        name: gitleaks
        description: Gitleaks is for detecting and preventing hardcoded secrets
        args: [--no-banner, --config=.gitleaks.toml]
        exclude: .secrets.baseline

  - repo: https://github.com/thoughtworks/talisman
    rev: v1.37.0
    hooks:
      - id: talisman-commit
        name: talisman (scans git to ensure that potential secrets or sensitive information)
        entry: cmd --githook pre-commit

#   ## TESTING HOOKS
#   - repo: https://github.com/chrysa/pre-commit-hooks-changelog
#     rev: v0.1.3
#     hooks:
#       - id: generate-changelog
#         files: 'changelog/.*(?<!\.yaml)(?<!\.yml)$'

#   - repo: https://github.com/rlindsgaard/pre-commit-commit-msg-hooks
#     rev: 0.1.0
#     hooks:
#       - id: check-description-max-length
#       - id: check-second-line-empty
#       - id: check-summary-capitalized
#       - id: check-summary-imperative
#       - id: check-summary-max-length
#       - id: check-summary-punctuation

#   - repo: https://github.com/geek-kb/python_docs_hook
#     rev: v0.1.13
#     hooks:
#       - id: python-docs

#   - repo: https://github.com/the-cafe/git-ai-commit
#     rev: v1.0.9
#     hooks:
#       - id: git-ai-commit
